version: '2'
services:
  db:
     image: mysql
     environment:
        MYSQL_ROOT_PASSWORD: sa123
        MYSQL_DATABASE: kdan
     ports:
      - 3306:3306
     volumes:
      - ./DB/sqls/:/docker-entrypoint-initdb.d/
     container_name: kdan_DB
  tomcat:
    depends_on:
      - db
    image: tomcat
    volumes:
      - ./phantommask.war:/usr/local/tomcat/webapps/phantommask.war
    ports:
      - '8080:8080'
    container_name: tomcat_Server
  